### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/Pugh#4]
The client reports that the site isn't showing up on Google searches. What basic tweaks can we make to improve search results?

**Comment by supportast** [comment]
We need to create google webmaster tool account and submit to google using that. then Google will start indexing the website.

**Comment by brettfarley** [comment]
Cool, can you handle that?

On April 11, 2016 at 3:47:57 PM, supportast (notifications@github.com) wrote:

We need to create google webmaster tool account and submit to google using that. then Google will start indexing the website.

**Comment by supportast** [comment]
Yes, I will handle. I just need to create a gmail account for that. I will post username/password here for future use.

**Comment by brettfarley** [comment]
Great thanks!

**Comment by supportast** [comment]
I have created google webmaster tool account and added the website in it .

**Comment by brettfarley** [comment]
Thanks. What are the next steps to improve ranking?

**Comment by supportast** [comment]
We need to choose keywords and start working on those. 
there are 2 steps of organic SEO, On page SEO and Off page SEO

in On page, We modify content according to keywords and update meta tags.

for Off page, we do link building and social sites posting on other websites and business listing, citation etc.

**Comment by brettfarley** [comment]
Ok, so here are some keywords: pugh, oklahoma, senate, edmond, air force

**Comment by supportast** [comment]
I will discuss this with you tonight.
