### ISSUE TITLE
Visual Editor

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/Pugh#5]
I can't seem to edit the home page with visual editor. Do we need to downgrade the WP version so this will work?

**Comment by supportast** [comment]
Yes downgrade or upgrade, new version of wordpress released 4.5.3 but still need to test.

**Comment by brettfarley** [comment]
I'll let you decide which is better option.

**Comment by supportast** [comment]
Working will be completing tomorrow .

**Comment by supportast** [comment]
done . Wp had to be downgraded
