### ISSUE TITLE
New pages

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/Pugh#8]
Please create a Photos page so all the pics on the site can be viewed and downloaded.

**Comment by supportast** [comment]
Please provide the images for this page and also any sample layout if you have

**Comment by brettfarley** [comment]
Please pull images from the site gallery. Any format is ok.

**Comment by supportast** [comment]
Page created . Download option  is pending .

**Comment by supportast** [comment]
Done  . Please check .
